### ISSUE TITLE
Create Empty Template of CSS, HTML, JS --DM

### ISSUE THREAD

**Issue by DamitryDong** [nss-evening-cohort-29/coding-champs-gitsub#1]
**User Story**
Need to set-up the files for project

**Acceptance Criteria**
1. Create empty css
2. Create Empty JS 
3. Create 7 parts that segment out each feature of the HTML: 
       --The 7 parts include: Profile area, navbar, footer, pinnable repository (for overview page), Repository, Project, Packages.
       --Connect css, JS, bootstrap

**Dependecies**
none

**Dev Notes**
none

**Comment by daniella-mcnair** [comment]
-Per class yesterday, we should use 4 html pages for each feature (overview, repositories, projects, packages)
